### ISSUE TITLE
Section qo'llanishini tavsiya qilaman.

### ISSUE THREAD

**Issue by IqboljonAbdumalikov** [ShokhrukhTurgunov/MayoqHub#3]
Bo'limlarga bo'lib ishlash oson bo`ladi, shunda.  :)
Barcha Elementlarga o'ziga xos class berish zarur, ro'yxatli ma'lumotlarni list "ul", "li" ko'rinishida berish qulayroq, menimcha.
Masalan:
<ul class="different_list">
         <li class="different_list_item">Snappy Process</li>
</ul>

div orqali yozishdan ko'ra,
<div class="process">
					<img src="icon-snappy-process.svg">
					<h3>Snappy process</h3>
					<p>Our application process can be completed in minutes, not hours. Don't get stuck filling in tedious forms.</p>
				</div>
		
				<div class="price">
					<img src="icon-affordable-prices.svg">
					<h3>Affordable Prices</h3>
					<p>We don't want to you worrying about high monthly costs. Our prices may be low, but still offer the best coverage possible</p>	
				</div>

				<div class="people">
					<img src="icon-people-first.svg">
					<h3>People First</h3>
					<p>Our olans are'nt full of conditions and clauses to prevent payouts. We make sure you're covered when you need it.</p>
				</div>	

https://github.com/ShokhrukhTurgunov/MayoqHub/blob/57643c1862506b7961e6e6bee4e7fe6910f29e5c/index.html#L24

**Comment by ShokhrukhTurgunov** [comment]
Rahmat maslahat uchun, bilmas edim. Umaman olganda html ,css ni endi o'rganayabman. I will change this tedious forms!
